name: Generate images.json

on:
  push:
    paths:
      - "images/**"
  workflow_dispatch:

permissions:
  contents: write

jobs:
  generate:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Generate images.json
        run: |
          echo "Generating images/images.json"
          ls -la images || true
          find images -maxdepth 1 -type f \( -iname '*.png' -o -iname '*.jpg' -o -iname '*.jpeg' -o -iname '*.webp' -o -iname '*.gif' \) \
            | sed 's|images/||' \
            | sort \
            | jq -R -s -c 'split("\n")[:-1]' > images/images.json

      - name: Commit images.json
        uses: stefanzweifel/git-auto-commit-action@v5
        with:
          commit_message: "Auto-generate images.json"
          file_pattern: images/images.json
